import { Button, Card, CardContent, Container, Grid, Stack, Typography } from '@mui/material'
import { Link as RouterLink } from 'react-router-dom'
import { ApiFeedback } from '../components/common/ApiFeedback'
import { useAccount } from '../hooks/useAccount'

export function AccountPage() {
  const { user, posters, orders } = useAccount()
  if (!user) return <Container maxWidth="sm" sx={{ py: 12, textAlign: 'center' }}><Typography variant="h1" sx={{ color: 'primary.main', fontSize: 55 }}>Your stories, in one place.</Typography><Typography color="text.secondary" mt={2}>Sign in to manage your poster projects and orders.</Typography><Button component={RouterLink} to="/signin" variant="contained" color="secondary" sx={{ mt: 3 }}>Sign in</Button></Container>
  return <Container maxWidth="lg" sx={{ py: { xs: 5, md: 8 } }}><Typography variant="overline" color="secondary" fontWeight={900}>Your account</Typography><Typography variant="h1" sx={{ color: 'primary.main', fontSize: { xs: 48, md: 65 } }}>Hello, {user.first_name}.</Typography><Grid container spacing={3} mt={2}><Grid size={{ xs: 12, md: 7 }}><Card><CardContent><Typography fontWeight={800} fontSize={20}>Poster projects</Typography><ApiFeedback loading={posters.isLoading} error={posters.isError} retry={posters.refetch} />{posters.data?.length === 0 && <Typography color="text.secondary" mt={2}>No projects yet. Your next story starts with a photo.</Typography>}<Stack spacing={1.5} mt={2}>{posters.data?.map((poster) => <Card variant="outlined" key={poster.id}><CardContent><Typography fontWeight={800}>Artwork project</Typography><Typography color="text.secondary" variant="body2">Status: {poster.status.replaceAll('_', ' ')}</Typography></CardContent></Card>)}</Stack><Button component={RouterLink} to="/products" variant="outlined" sx={{ mt: 3 }}>Create a poster</Button></CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card><CardContent><Typography fontWeight={800} fontSize={20}>Orders</Typography><ApiFeedback loading={orders.isLoading} error={orders.isError} retry={orders.refetch} />{orders.data?.length === 0 && <Typography color="text.secondary" mt={2}>Your completed orders will appear here.</Typography>}<Stack spacing={1.5} mt={2}>{orders.data?.map((order) => <Card variant="outlined" key={order.id}><CardContent><Typography fontWeight={800}>{order.order_number}</Typography><Typography color="text.secondary" variant="body2">{order.status.replaceAll('_', ' ')} · ₹{Number(order.total).toLocaleString('en-IN')}</Typography></CardContent></Card>)}</Stack></CardContent></Card></Grid></Grid></Container>
}
